# FROM node:latest
FROM node:23-bookworm-slim AS builder
LABEL maintaner='y-yoshimoto'
# 環境変数を設定する
ENV NODE_ENV=production
#ENV NODE_ENV=development
ENV APPNAME=app
# 引数から環境変数を定義する
# ARG VITE_ROUTER_BASENAME="/portal"
# ARG VITE_MOCK_ENABLED="false"
# ENV VITE_ROUTER_BASENAME=${VITE_ROUTER_BASENAME}
# ENV VITE_MOCK_ENABLED=${VITE_MOCK_ENABLED}

# アプリケーションディレクトリ作成/コピー
RUN mkdir -p /$APPNAME
WORKDIR /$APPNAME
# パッケージインストール(viteインストールのため --devオプション付き)
COPY ./package.json /$APPNAME/package.json
RUN npm install --include=dev
RUN npx playwright install-deps
# アプリケーションのビルド
#ENV NODE_ENV=production
COPY ./ /$APPNAME/
RUN ls -al /$APPNAME/ && echo $NODE_ENV
RUN npm run build

# React App set Nginx
FROM nginx
LABEL  maintainer "y.yoshimoto"
ENV APPNAME=app
# コンテツファイルの設置
COPY --from=builder /$APPNAME/dist/ /usr/share/nginx/html/
#RUN mkdir -p /usr/share/nginx/html/sampleData 
# nginx設定ファイルの設置
#COPY ./deploy/nginx.conf /etc/nginx/nginx.conf
#COPY ./deploy/server.conf /etc/nginx/conf.d/server.conf 
# コンテナ実行時の動作設定
EXPOSE 80 443 5173
ENTRYPOINT ["/usr/sbin/nginx", "-g", "daemon off;", "-c", "/etc/nginx/nginx.conf"]
