apiVersion: v1
kind: Deployment
metadata:
  name: hello-node
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: hello-node
    spec:
      containers:
      - name: hello-node
        image: hello-node:v1
        ports:
      	- containerPort: 8080
