name: Pull Request Action

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  printLog:
    runs-on: ubuntu-latest

    steps:
      - name: echo Pull Request Action
        run: echo "Pull Request Action"

      - name: Add comment to PR
        uses: actions/github-script@v6
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Action has been triggered'
            })
